/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.*;
import javax.swing.*;
import clases.Conexion;
import java.sql.*;

/**
 *
 * @author agust
 */
public class GraficarMarcas extends javax.swing.JFrame {

    String User;
    int Acer, Alienware, Apple, Asus, Brother, Dell, Hp, Lenovo, Samsung, Toshiba, Xerox;
    String[] Vector_Marcas_Nombre = new String[11];
    int[] Vector_Marcas_Cantidad = new int[11];

    /**
     * Creates new form GraficarEstatus
     */
    public GraficarMarcas() {
        initComponents();
        User = Login.User;
        setSize(550, 450);
        setResizable(false);
        setTitle("Técnico - Sesión de " + User);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        try {
            Connection cn = Conexion.Conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select Marca,count(Marca) as Marcas from equipos group by Marca");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int Position = 0;
                do {
                    Vector_Marcas_Nombre[Position] = rs.getString(1);
                    Vector_Marcas_Cantidad[Position] = rs.getInt(2);

                    if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("Acer")) {
                        Acer = Vector_Marcas_Cantidad[Position];
                    } else if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("Alienware")) {
                        Alienware = Vector_Marcas_Cantidad[Position];
                    } else if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("Apple")) {
                        Apple = Vector_Marcas_Cantidad[Position];
                    } else if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("Asus")) {
                        Asus = Vector_Marcas_Cantidad[Position];
                    } else if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("Brother")) {
                        Brother = Vector_Marcas_Cantidad[Position];
                    } else if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("Dell")) {
                        Dell = Vector_Marcas_Cantidad[Position];
                    } else if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("HP")) {
                        Hp = Vector_Marcas_Cantidad[Position];
                    } else if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("Lenovo")) {
                        Lenovo = Vector_Marcas_Cantidad[Position];
                    } else if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("Samsung")) {
                        Samsung = Vector_Marcas_Cantidad[Position];
                    } else if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("Toshiba")) {
                        Toshiba = Vector_Marcas_Cantidad[Position];
                    } else if (Vector_Marcas_Nombre[Position].equalsIgnoreCase("Xerox")) {
                        Xerox = Vector_Marcas_Cantidad[Position];
                    }

                    Position++;

                } while (rs.next());
            }
        } catch (SQLException e) {
            System.err.println("Error en la consulta." + e);
            JOptionPane.showMessageDialog(null, "¡¡Error en consultar datos!!, Contacte al administrador.");
        }

        repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gráfica de Marcas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficarMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficarMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficarMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficarMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficarMarcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(Graphics g) {
        super.paint(g);

        int Total_Marca = Acer + Alienware + Apple + Asus + Brother + Dell + Hp + Lenovo + Samsung + Toshiba + Xerox;

        int Grado_Acer = Acer * 360 / Total_Marca;
        int Grado_Alienware = Alienware * 360 / Total_Marca;
        int Grado_Apple = Apple * 360 / Total_Marca;
        int Grado_Asus = Asus * 360 / Total_Marca;
        int Grado_Brother = Brother * 360 / Total_Marca;
        int Grado_Dell = Dell * 360 / Total_Marca;
        int Grado_Hp = Hp * 360 / Total_Marca;
        int Grado_Lenovo = Lenovo * 360 / Total_Marca;
        int Grado_Samsung = Samsung * 360 / Total_Marca;
        int Grado_Toshiba = Toshiba * 360 / Total_Marca;
        int Grado_Xerox = Xerox * 360 / Total_Marca;

        //Marca Acer
        g.setColor(new Color(175, 122, 197));//Color Morado
        g.fillArc(25, 100, 270, 270, 0, Grado_Acer);
        g.fillRect(310, 120, 20, 20);
        g.drawString("Acer:" + Acer, 340, 135);

        //Marca Alienware
        g.setColor(new Color(0, 255, 0));//Color Verde
        g.fillArc(25, 100, 270, 270, Grado_Acer, Grado_Alienware);
        g.fillRect(310, 150, 20, 20);
        g.drawString("Alienware:" + Alienware, 340, 165);

        //Marca Apple
        g.setColor(new Color(0, 255, 255));//Color Verde agua
        g.fillArc(25, 100, 270, 270, Grado_Acer + Grado_Alienware, Grado_Apple);
        g.fillRect(310, 180, 20, 20);
        g.drawString("Apple:" + Apple, 340, 195);

        //Marca Asus
        g.setColor(new Color(55, 0, 255));//Color Azul
        g.fillArc(25, 100, 270, 270, Grado_Acer + Grado_Alienware + Grado_Apple, Grado_Asus);
        g.fillRect(310, 210, 20, 20);
        g.drawString("Asus:" + Asus, 340, 225);

        //Marca Bother
        g.setColor(new Color(255, 255, 255));//Color Blanco
        g.fillArc(25, 100, 270, 270, Grado_Acer + Grado_Alienware + Grado_Apple + Grado_Asus, Grado_Brother);
        g.fillRect(310, 240, 20, 20);
        g.drawString("Brother:" + Brother, 340, 255);

        //Marca Dell
        g.setColor(new Color(247, 220, 111));//Color Amarillo
        g.fillArc(25, 100, 270, 270, Grado_Acer + Grado_Alienware + Grado_Apple + Grado_Asus + Grado_Brother, Grado_Dell);
        g.fillRect(310, 270, 20, 20);
        g.drawString("Dell:" + Dell, 340, 285);

        //Marca Hp
        g.setColor(new Color(21, 42, 160));//Color Azul Marino
        g.fillArc(25, 100, 270, 270, Grado_Acer + Grado_Alienware + Grado_Apple + Grado_Asus + Grado_Brother + Grado_Dell, Grado_Hp);
        g.fillRect(310, 300, 20, 20);
        g.drawString("Hp:" + Hp, 340, 315);

        //Marca Lenovo
        g.setColor(new Color(215, 96, 0));//Color Naranja
        g.fillArc(25, 100, 270, 270, Grado_Acer + Grado_Alienware + Grado_Apple + Grado_Asus + Grado_Brother + Grado_Dell + Grado_Hp, Grado_Lenovo);
        g.fillRect(310, 330, 20, 20);
        g.drawString("Lenovo:" + Lenovo, 340, 345);

        //Marca Samsung
        g.setColor(new Color(215, 96, 140));//Color Rosa
        g.fillArc(25, 100, 270, 270, Grado_Acer + Grado_Alienware + Grado_Apple + Grado_Asus + Grado_Brother + Grado_Dell + Grado_Hp + Grado_Lenovo, Grado_Samsung);
        g.fillRect(430, 120, 20, 20);
        g.drawString("Samsung:" + Samsung, 460, 135);

        //Marca Toshiba
        g.setColor(new Color(215, 196, 25));//Color Amarillo Canario
        g.fillArc(25, 100, 270, 270, Grado_Acer + Grado_Alienware + Grado_Apple + Grado_Asus + Grado_Brother + Grado_Dell + Grado_Hp + Grado_Lenovo + Grado_Samsung, Grado_Toshiba);
        g.fillRect(430, 150, 20, 20);
        g.drawString("Toshiba:" + Toshiba, 460, 165);

        //Marca Xerox
        g.setColor(new Color(93, 173, 226));//Color Celeste
        g.fillArc(25, 100, 270, 270, Grado_Acer + Grado_Acer + Grado_Alienware + Grado_Apple + Grado_Asus + Grado_Brother + Grado_Dell + Grado_Hp + Grado_Lenovo + Grado_Samsung + Grado_Toshiba, Grado_Xerox);
        g.fillRect(430, 180, 20, 20);
        g.drawString("Xerox:" + Xerox, 460, 195);

    }

}
