/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.*;
import javax.swing.*;
import java.sql.*;
import clases.Conexion;

/**
 *
 * @author agust
 */
public class InformacionUsuario extends javax.swing.JFrame {

    String User = "", User_Update = "";
    int Id;

    /**
     * Creates new form InformacionUsuario
     */
    public InformacionUsuario() {
        initComponents();
        User = Login.User;
        User_Update = GestionarUsuarios.User_Update;

        setTitle("Información del usuario " + User_Update + " - Sesión de " + User);
        setLocationRelativeTo(null);
        setSize(630, 450);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        jLabel_Titulo.setText("Información del usuario " + User_Update);

        try {
            Connection cn = Conexion.Conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from usuarios where User = '" + User_Update + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                Id = rs.getInt("Id_Usuarios");

                txt_Nombre.setText(rs.getString("Nombre_Usuario"));
                txt_Email.setText(rs.getString("Email_Usuario"));
                txt_Telefono.setText(rs.getString("Telefono_Usuario"));
                txt_UserName.setText(rs.getString("User"));
                txt_Registradopor.setText(rs.getString("Registrado_Por"));

                cmb_Niveles.setSelectedItem(rs.getString("Tipo_Nivel"));
                cmb_Estatus.setSelectedItem(rs.getString("Estatus"));
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en cargar usuario. " + e);
            JOptionPane.showMessageDialog(null, "¡¡Error al cargar!!, contacte con el administrador.");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_Telefono = new javax.swing.JLabel();
        jLabel_Permisosde = new javax.swing.JLabel();
        jLabel_UserName = new javax.swing.JLabel();
        jLabel_Estatus = new javax.swing.JLabel();
        jLabel_Registradopor = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        txt_UserName = new javax.swing.JTextField();
        txt_Registradopor = new javax.swing.JTextField();
        cmb_Estatus = new javax.swing.JComboBox<>();
        cmb_Niveles = new javax.swing.JComboBox<>();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_RestaurarPassword = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Información del Usuario");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre.setText("Nombre:");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel_Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Email.setText("Email:");
        getContentPane().add(jLabel_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel_Telefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Telefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Telefono.setText("Telefono:");
        getContentPane().add(jLabel_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel_Permisosde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Permisosde.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Permisosde.setText("Permisos de:");
        getContentPane().add(jLabel_Permisosde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel_UserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_UserName.setText("UserName:");
        getContentPane().add(jLabel_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel_Estatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Estatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Estatus.setText("Estatus:");
        getContentPane().add(jLabel_Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel_Registradopor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Registradopor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registradopor.setText("Registrado por:");
        getContentPane().add(jLabel_Registradopor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        txt_Nombre.setBackground(new java.awt.Color(153, 153, 255));
        txt_Nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_Email.setBackground(new java.awt.Color(153, 153, 255));
        txt_Email.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Email.setForeground(new java.awt.Color(255, 255, 255));
        txt_Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        txt_Telefono.setBackground(new java.awt.Color(153, 153, 255));
        txt_Telefono.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Telefono.setForeground(new java.awt.Color(255, 255, 255));
        txt_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Telefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        txt_UserName.setBackground(new java.awt.Color(153, 153, 255));
        txt_UserName.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_UserName.setForeground(new java.awt.Color(255, 255, 255));
        txt_UserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_UserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

        txt_Registradopor.setBackground(new java.awt.Color(153, 153, 255));
        txt_Registradopor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Registradopor.setForeground(new java.awt.Color(255, 255, 255));
        txt_Registradopor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Registradopor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_Registradopor.setEnabled(false);
        getContentPane().add(txt_Registradopor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, -1));

        cmb_Estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(cmb_Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        cmb_Niveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(cmb_Niveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jButton_Actualizar.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Actualizar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Actualizar.setText("Actualizar Usuario");
        jButton_Actualizar.setBorder(null);
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 210, 35));

        jButton_RestaurarPassword.setBackground(new java.awt.Color(153, 153, 255));
        jButton_RestaurarPassword.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_RestaurarPassword.setForeground(new java.awt.Color(255, 255, 255));
        jButton_RestaurarPassword.setText("Restaurar Password");
        jButton_RestaurarPassword.setBorder(null);
        jButton_RestaurarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RestaurarPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RestaurarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 210, 35));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
        // TODO add your handling code here:
        int Permisos_cmb, Estatus_cmb, Validacion = 0;
        String Nombre, Mail, Telefono, UserName, Pass, Permisos_String = "", Estatus_String = "";

        Nombre = txt_Nombre.getText().trim();
        Mail = txt_Email.getText().trim();
        Telefono = txt_Telefono.getText().trim();
        UserName = txt_UserName.getText().trim();
        Permisos_cmb = cmb_Niveles.getSelectedIndex() + 1;
        Estatus_cmb = cmb_Estatus.getSelectedIndex() + 1;

        if (Nombre.equals("")) {
            txt_Nombre.setBackground(Color.RED);
            Validacion++;
        }
        if (Mail.equals("")) {
            txt_Email.setBackground(Color.RED);
            Validacion++;
        }
        if (Telefono.equals("")) {
            txt_Telefono.setBackground(Color.RED);
            Validacion++;
        }
        if (UserName.equals("")) {
            txt_UserName.setBackground(Color.RED);
            Validacion++;
        }

        if (Validacion == 0) {
            if (Permisos_cmb == 1) {
                Permisos_String = "Administrador";
            } else if (Permisos_cmb == 2) {
                Permisos_String = "Capturista";
            } else if (Permisos_cmb == 3) {
                Permisos_String = "Tecnico";
            }
            
            if (Estatus_cmb == 1) {
                Estatus_String = "Activo";
            } else if (Estatus_cmb == 2) {
                Estatus_String = "Inactivo";
            } 
            
            try {
                Connection cn = Conexion.Conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select User from usuarios where User = '" + UserName + "' and not Id_Usuarios = '" + Id + "'");
                ResultSet rs = pst.executeQuery();
                
                if(rs.next()){
                    txt_UserName.setBackground(Color.RED);
                    JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible.");
                    cn.close();
                }else{
                    Connection cn2 = Conexion.Conectar();
                    PreparedStatement pst2 = cn2.prepareStatement(
                            "update usuarios set Nombre_Usuario = ?,Email_Usuario = ?,Telefono_Usuario = ?,User = ?,Tipo_Nivel = ?,Estatus = ?"
                                    + "where Id_Usuarios = '" + Id + "'");
                    
                    pst2.setString(1, Nombre);
                    pst2.setString(2,Mail);
                    pst2.setString(3,Telefono);
                    pst2.setString(4,UserName);
                    pst2.setString(5,Permisos_String);
                    pst2.setString(6,Estatus_String);
                    
                    pst2.executeUpdate();
                    cn2.close();
                    
                    JOptionPane.showMessageDialog(null, "Modificación Correcta.");
                }
            } catch (SQLException e) {
                System.err.println("Error al actualizar. " + e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_RestaurarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RestaurarPasswordActionPerformed
        // TODO add your handling code here:
        RestaurarPassword restaurarPass = new RestaurarPassword();
        restaurarPass.setVisible(true);
    }//GEN-LAST:event_jButton_RestaurarPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_Estatus;
    private javax.swing.JComboBox<String> cmb_Niveles;
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_RestaurarPassword;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Estatus;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Permisosde;
    private javax.swing.JLabel jLabel_Registradopor;
    private javax.swing.JLabel jLabel_Telefono;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Registradopor;
    private javax.swing.JTextField txt_Telefono;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
