/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author agust
 */
public class RegistrarEquipo extends javax.swing.JFrame {

    int IdCliente_Update = 0;
    String User = "", Nom_Cliente = "";

    /**
     * Creates new form RegistrarEquipo
     */
    public RegistrarEquipo() {
        initComponents();
        User = Login.User;
        IdCliente_Update = GestionarClientes.IdCliente_update;

        try {
            Connection cn = Conexion.Conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select Nombre_Clientes from clientes where Id_Clientes = '" + IdCliente_Update + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                Nom_Cliente = rs.getString("Nombre_Clientes");
            }
        } catch (SQLException e) {
            System.err.println("Error al consultar el nombre del cliente.");
        }

        setLocationRelativeTo(null);
        setSize(630, 445);
        setResizable(false);
        setTitle("Registrar nuevo equipo para " + Nom_Cliente);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        txt_NombreCliente.setText(Nom_Cliente);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_TipoEquipo = new javax.swing.JLabel();
        jLabel_Marca = new javax.swing.JLabel();
        jLabel_Modelo = new javax.swing.JLabel();
        jLabel_NumerodeSerie = new javax.swing.JLabel();
        jLabel_DañoReportado = new javax.swing.JLabel();
        txt_NombreCliente = new javax.swing.JTextField();
        txt_Modelo = new javax.swing.JTextField();
        txt_NumerodeSerie = new javax.swing.JTextField();
        cmb_TipoEquipo = new javax.swing.JComboBox<>();
        cmb_Marca = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_Observaciones = new javax.swing.JTextPane();
        jButton_Registrar = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Registro de Equipo");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre.setText("Nombre del Cliente:");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel_TipoEquipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_TipoEquipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TipoEquipo.setText("Tipo de Equipo:");
        getContentPane().add(jLabel_TipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel_Marca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Marca.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Marca.setText("Marca:");
        getContentPane().add(jLabel_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel_Modelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Modelo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Modelo.setText("Modelo:");
        getContentPane().add(jLabel_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel_NumerodeSerie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_NumerodeSerie.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NumerodeSerie.setText("Número de Serie:");
        getContentPane().add(jLabel_NumerodeSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel_DañoReportado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_DañoReportado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DañoReportado.setText("Daño Reportado y Observaciones:");
        getContentPane().add(jLabel_DañoReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        txt_NombreCliente.setBackground(new java.awt.Color(153, 153, 255));
        txt_NombreCliente.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_NombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txt_NombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NombreCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        txt_Modelo.setBackground(new java.awt.Color(153, 153, 255));
        txt_Modelo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_Modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Modelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, -1));

        txt_NumerodeSerie.setBackground(new java.awt.Color(153, 153, 255));
        txt_NumerodeSerie.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_NumerodeSerie.setForeground(new java.awt.Color(255, 255, 255));
        txt_NumerodeSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NumerodeSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_NumerodeSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 210, -1));

        cmb_TipoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifuncional" }));
        getContentPane().add(cmb_TipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cmb_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Alienware", "Apple", "Asus", "Brother", "Dell", "Hp", "Lenovo", "Samsung", "Toshiba", "Xerox" }));
        getContentPane().add(cmb_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jScrollPane1.setViewportView(jTextPane_Observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 330, 230));

        jButton_Registrar.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Registrar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registrar.setText("Registrar Equipo");
        jButton_Registrar.setBorder(null);
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 210, 35));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 445));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed
        // TODO add your handling code here:
        int Validacion = 0;
        String Tipo_Equipo, Marca, Modelo, Num_Serie, Dia_Ingreso, Mes_Ingreso, Anio_Ingreso, Estatus, Observaciones;

        Tipo_Equipo = cmb_TipoEquipo.getSelectedItem().toString();
        Marca = cmb_Marca.getSelectedItem().toString();
        Modelo = txt_Modelo.getText().trim();
        Num_Serie = txt_NumerodeSerie.getText().trim();
        Observaciones = jTextPane_Observaciones.getText();
        Estatus = "Nuevo Ingreso";

        Calendar calendario = Calendar.getInstance();

        Dia_Ingreso = Integer.toString(calendario.get(Calendar.DATE));
        Mes_Ingreso = Integer.toString(calendario.get(Calendar.MONTH));
        Anio_Ingreso = Integer.toString(calendario.get(Calendar.YEAR));

        if (Modelo.equals("")) {
            txt_Modelo.setBackground(Color.RED);
            Validacion++;
        }
        if (Num_Serie.equals("")) {
            txt_NumerodeSerie.setBackground(Color.RED);
            Validacion++;
        }
        if (Observaciones.equals("")) {
            jTextPane_Observaciones.setText("Sin Observaciones.");
        }

        if (Validacion == 0) {
            try {
                Connection cn = Conexion.Conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "insert into equipos values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
 
                 pst.setInt(1,0);
                 pst.setInt(2,IdCliente_Update);
                 pst.setString(3, Tipo_Equipo);
                 pst.setString(4, Marca);
                 pst.setString(5, Modelo);
                 pst.setString(6, Num_Serie);
                 pst.setString(7, Dia_Ingreso);
                 pst.setString(8, Mes_Ingreso + 1);
                 pst.setString(9, Anio_Ingreso);
                 pst.setString(10, Observaciones);
                 pst.setString(11, Estatus);
                 pst.setString(12, User);
                 pst.setString(13, "");
                 pst.setString(14, "");
                 
                 pst.executeUpdate();
                 cn.close();
                 
                 txt_NombreCliente.setBackground(Color.GREEN);
                 txt_Modelo.setBackground(Color.GREEN);
                 txt_NumerodeSerie.setBackground(Color.GREEN);
                 
                 JOptionPane.showMessageDialog(null, "Registro Exitoso.");
                 this.dispose();
                 
            } catch (SQLException e) {
                System.err.println("Error al registrar equipo. " + e);
                JOptionPane.showMessageDialog(null, "¡¡Error al registrar equipo!!, contacte al administrador.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
        }
    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_Marca;
    private javax.swing.JComboBox<String> cmb_TipoEquipo;
    private javax.swing.JButton jButton_Registrar;
    private javax.swing.JLabel jLabel_DañoReportado;
    private javax.swing.JLabel jLabel_Marca;
    private javax.swing.JLabel jLabel_Modelo;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_NumerodeSerie;
    private javax.swing.JLabel jLabel_TipoEquipo;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane_Observaciones;
    private javax.swing.JTextField txt_Modelo;
    private javax.swing.JTextField txt_NombreCliente;
    private javax.swing.JTextField txt_NumerodeSerie;
    // End of variables declaration//GEN-END:variables
}
